script:
  - "bundle exec rake neo4j:install['community-2.2.0-M02'] neo4j:start default --trace"language: ruby
language: ruby
rvm:
- 2.0.0-p247
- 2.1.0
email:
  on_success: never
  on_failure: never
branches:
  only:
    - gh-pages
